language: node_js

node_js:
  - "10"

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"

script:
  - yarn ng build ngx-spine
  - yarn ng build ngx-spine-demos --prod

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist/ngx-spine-demos/
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
